server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CONSULTANT-SERVICE
          uri: lb://CONSULTANT-SERVICE
          predicates:
            - Path=/consultants/**
          filters:
            - name: CircuitBreaker
              args:
                name: CONSULTANT-SERVICE
                fallbackuri: forward:/consultantServiceFallBack

        - id: TEAM-SERVICE
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/teams/**
          filters:
            - name: CircuitBreaker
              args:
                name: TEAM-SERVICE
                fallbackuri: forward:/teamServiceFallBack

        - id: ENGAGEMENT-SERVICE
          uri: lb://ENGAGEMENT-SERVICE
          predicates:
            - Path=/engagements/**
          filters:
            - name: CircuitBreaker
              args:
                name: ENGAGEMENT-SERVICE
                fallbackuri: forward:/engagementServiceFallBack

        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
          filters:
            - name: CircuitBreaker
              args:
                name: CUSTOMER-SERVICE
                fallbackuri: forward:/customerServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
